language: c
sudo: false
script: make -f sys/unix/GNUmakefile install
compiler:
  - gcc
  - clang
notifications:
  irc:
    channels:
        - "irc.freenode.net#slashemextended"
        - "irc.freenode.net#em.slashem.me"
    skip_join: true
