language: c
sudo: false
script: make -f sys/unix/GNUmakefile install
notifications:
  irc:
    channels:
        - "irc.freenode.net#slashemextended"
        - "irc.freenode.net#em.slashem.me"
    skip_join: true
matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
    - os: osx
      compiler: gcc-4.9
      osx_image: xcode8.0
    - os: osx
      compiler: clang
      osx_image: xcode8.0
